In [1]:
run eda_sugar.py

In [2]:
grouped_by_user.head()

user_id  total_app_opened sign_up_date  min_app_open_day   last_day  \
0        2                22   2016-05-01                 1 2016-06-30   
1        3                14   2016-07-20                 1 2016-07-23   
2        5                 4   2016-05-22                 1 2016-07-17   
3        6                 5   2016-05-16                 1 2016-06-09   
4        8                16   2016-05-02                 1 2016-08-30   

   max_app_open_day 1wfrom_start  open_1w  open_after_1w  user_app_age  \
0                 3   2016-05-08        3           19.0       60 days   
1                 6   2016-07-27       14            NaN        3 days   
2                 2   2016-05-29        2            2.0       56 days   
3                 2   2016-05-23        2            3.0       24 days   
4                 2   2016-05-09        3           13.0      120 days   

   accute  critical  weight_input  
0     1.0       0.0           NaN  
1     0.0       0.0           NaN  
2     NaN       NaN           1.0  
3     0.0       1.0           NaN  
4     0.0       0.0           NaN

In [3]:
carb_ent.head()

Date  value  user_id
0  2016-05-15      1  11782.0
1  2016-05-23      2  11782.0
2  2016-06-10      1  11782.0
3  2016-06-13      3  11782.0
4  2016-06-26      1  11782.0

In [5]:
carb_grouped = carb_ent.groupby('user_id').sum().reset_index()

In [6]:
carb_grouped.head()

user_id  value
0      3.0      1
1      5.0      1
2     14.0      1
3     35.0      2
4     38.0     26

In [8]:
carb_ent = carb_ent.fillna(55555)
carb_ent['user_id']= carb_ent['user_id'].astype(int)

In [9]:
carb_grouped = carb_ent.groupby('user_id').sum().reset_index()

In [10]:
carb_grouped.columns = ['user_id', 'carb_ent']


In [11]:
    grouped_by_user =grouped_by_user.merge(carb_grouped,how='left', left_on='user_id', right_on='user_id')


In [12]:
grouped_by_user.head()

user_id  total_app_opened sign_up_date  min_app_open_day   last_day  \
0        2                22   2016-05-01                 1 2016-06-30   
1        3                14   2016-07-20                 1 2016-07-23   
2        5                 4   2016-05-22                 1 2016-07-17   
3        6                 5   2016-05-16                 1 2016-06-09   
4        8                16   2016-05-02                 1 2016-08-30   

   max_app_open_day 1wfrom_start  open_1w  open_after_1w  user_app_age  \
0                 3   2016-05-08        3           19.0       60 days   
1                 6   2016-07-27       14            NaN        3 days   
2                 2   2016-05-29        2            2.0       56 days   
3                 2   2016-05-23        2            3.0       24 days   
4                 2   2016-05-09        3           13.0      120 days   

   accute  critical  weight_input  carb_ent  
0     1.0       0.0           NaN       NaN  
1     0.0       0.0           NaN       1.0  
2     NaN       NaN           1.0       1.0  
3     0.0       1.0           NaN       NaN  
4     0.0       0.0           NaN       NaN

In [13]:
carb_ent.head()

Date  value  user_id
0  2016-05-15      1    11782
1  2016-05-23      2    11782
2  2016-06-10      1    11782
3  2016-06-13      3    11782
4  2016-06-26      1    11782

In [14]:
user_profiles.head()

user_id properties.BG_Schedule properties.dateOfFirstLaunch  \
0        1                    NaN                          NaT   
1        2                   3day          2016-03-14 18:13:53   
2        3                   1day          2016-07-20 18:50:42   
3        4                    NaN          2016-06-20 07:11:08   
4        5                    NaN          2016-05-22 10:04:37   

  properties.user.diabetes.type properties.Meal_Reminders_Set  \
0                           NaN                           NaN   
1                       Type II                           NaN   
2                       Type II                         False   
3                           NaN                           NaN   
4                       Type II                           NaN   

  properties.TrackingExerciseMinutes  properties.Total_BG_Reminders  \
0                                NaN                            NaN   
1                                NaN                            NaN   
2                                NaN                            NaN   
3                                NaN                            NaN   
4                                NaN                            NaN   

   properties.numAppOpenLifeTime properties.UserTreatmentType  \
0                            NaN                          NaN   
1                            NaN                          NaN   
2                            NaN                          NaN   
3                            NaN                          NaN   
4                            NaN                          NaN   

   properties.carbBudget   ...    properties.CarbEntryPreference Gestational  \
0                    NaN   ...                               NaN         0.0   
1                  180.0   ...                          estimate         0.0   
2                  180.0   ...                          estimate         0.0   
3                  130.0   ...                           numeric         0.0   
4                  130.0   ...                           numeric         0.0   

   LADA  Lada  None  Other  Pre-diabetic  Prediabetes  Type I  Type II  
0   0.0   0.0   0.0    0.0           0.0          0.0     0.0      0.0  
1   0.0   0.0   0.0    0.0           0.0          0.0     0.0      1.0  
2   0.0   0.0   0.0    0.0           0.0          0.0     0.0      1.0  
3   0.0   0.0   0.0    0.0           0.0          0.0     0.0      0.0  
4   0.0   0.0   0.0    0.0           0.0          0.0     0.0      1.0  

[5 rows x 21 columns]

In [25]:
user_profiles.isnull().all()


user_id                               False
properties.BG_Schedule                False
properties.dateOfFirstLaunch          False
properties.user.diabetes.type         False
properties.Meal_Reminders_Set         False
properties.TrackingExerciseMinutes    False
properties.Total_BG_Reminders         False
properties.numAppOpenLifeTime         False
properties.UserTreatmentType          False
properties.carbBudget                 False
properties.gender                     False
properties.CarbEntryPreference        False
Gestational                           False
LADA                                  False
Lada                                  False
None                                  False
Other                                 False
Pre-diabetic                          False
Prediabetes                           False
Type I                                False
Type II                               False
dtype: bool

In [19]:
grouped_by_user.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23655 entries, 0 to 23654
Data columns (total 14 columns):
user_id             23655 non-null int64
total_app_opened    23655 non-null int64
sign_up_date        23655 non-null datetime64[ns]
min_app_open_day    23655 non-null int64
last_day            23655 non-null datetime64[ns]
max_app_open_day    23655 non-null int64
1wfrom_start        23655 non-null datetime64[ns]
open_1w             23655 non-null int64
open_after_1w       11413 non-null float64
user_app_age        23655 non-null timedelta64[ns]
accute              15390 non-null float64
critical            15390 non-null float64
weight_input        11809 non-null float64
carb_ent            5742 non-null float64
dtypes: datetime64[ns](3), float64(5), int64(5), timedelta64[ns](1)
memory usage: 2.7 MB


In [26]:
user_profiles = pd.read_csv('data/UserProfiles.csv').drop(['Unnamed: 0'],axis=1)
df.ix[df.index[(df.T == np.nan).sum() > 1]]


In [27]:
user_profiles.columns

Index([u'user_id', u'properties.BG_Schedule', u'properties.dateOfFirstLaunch',
       u'properties.user.diabetes.type', u'properties.Meal_Reminders_Set',
       u'properties.TrackingExerciseMinutes', u'properties.Total_BG_Reminders',
       u'properties.numAppOpenLifeTime', u'properties.UserTreatmentType',
       u'properties.carbBudget', u'properties.gender',
       u'properties.CarbEntryPreference'],
      dtype='object')

In [28]:
user_profiles

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43194 entries, 0 to 43193
Data columns (total 12 columns):
user_id                               43194 non-null int64
properties.BG_Schedule                8288 non-null object
properties.dateOfFirstLaunch          37508 non-null object
properties.user.diabetes.type         34110 non-null object
properties.Meal_Reminders_Set         4222 non-null object
properties.TrackingExerciseMinutes    21102 non-null object
properties.Total_BG_Reminders         6441 non-null float64
properties.numAppOpenLifeTime         146 non-null float64
properties.UserTreatmentType          42 non-null object
properties.carbBudget                 30112 non-null float64
properties.gender                     31664 non-null object
properties.CarbEntryPreference        15937 non-null object
dtypes: float64(3), int64(1), object(8)
memory usage: 4.0+ MB


In [51]:
user_profiles['user_id'].unique().shape

(43194,)

In [31]:
user_profiles.shape

(43194, 12)

In [38]:
user_profiles['properties.UserTreatmentType'].unique()

array([nan, 'none', 'Both', 'Meds'], dtype=object)

In [ ]:
user_profiles['properties.UserTreatmentType'].unique()

In [39]:
user_profiles['properties.BG_Schedule'].unique()

array([nan, '3day', '1day', '2day', '6day', '5day', '12day', '4day',
       '7day', '2month', '8day', '6week', '10day', '2week', '8month',
       '3week', '4week', '1week', '7week', '10week', '6month', '5week',
       '1month', '11month', '9day', '11day', '12month', '4month', '3month',
       '12week'], dtype=object)

In [41]:
user_profiles['properties.user.diabetes.type'].unique()

array([nan, 'Type II', 'Type I', 'Prediabetes', 'None', 'Gestational',
       'LADA', 'Lada', 'Pre-diabetic', 'Other'], dtype=object)

In [42]:
user_profiles['properties.Meal_Reminders_Set'].unique()

array([nan, False, True], dtype=object)

In [43]:
user_profiles['properties.TrackingExerciseMinutes'].unique()

array([nan, False, True], dtype=object)

In [44]:
user_profiles['properties.Total_BG_Reminders'].unique()

array([ nan,   1.,   2.,   5.,   6.,   3.,   4.,   8.,   7.,  10.,   9.,
        11.])

In [45]:
user_profiles['properties.numAppOpenLifeTime'].unique()

array([ nan,   1.,   2.,  10.,  11.,   4.,  24.,   3.,   6.,  14.,  18.,
         7.,  37.,  15.,   5.,   8.,  13.,  25.,  39.,   9.,  19.,  16.,
        58.,  29.,  26.])

In [46]:
user_profiles['properties.carbBudget'].unique()

array([   nan,   180.,   130.,   120.,   177.,    67.,   110.,    30.,
         300.,   225.,    50.,   100.,   250.,   200.,   150.,  2000.,
          20.,    15.,   140.,   240.,   147.,    75.,   190.,   135.,
         168.,   195.,   500.,   188.,    25.,    60.,   260.,   115.,
         210.,   270.,    90.,   205.,   170.,   220.,   162.,   175.,
         185.,   400.,    80.,   360.,   256.,   165.,   255.,   450.,
         288.,   320.,   215.,  1000.,    45.,   167.,  1500.,    68.,
          70.,   206.,   236.,   131.,   160.,    63.,    65.,     4.,
         233.,   540.,   230.,     5.,   125.,    10.,  1850.,   218.,
         267.,   228.,   213.,   104.,   310.,    35.,   290.,   350.,
         105.,   217.,   280.,    40.,   425.,   192.,   144.,   169.,
          28.,    57.,    14.,   286.,   145.,   315.,   460.,  2700.,
          42.,    48.,  1800.,   330.,    95.,   164.,   176.,    85.,
         113.,   650.,   293.,    44.,   424.,  1300.,   325.,    99.,
      

In [47]:
user_profiles['properties.gender'].unique()

array([nan, 'Male', 'Female'], dtype=object)

In [49]:
user_profiles['properties.CarbEntryPreference'].unique()

array([nan, 'estimate', 'numeric'], dtype=object)

In [30]:
user_profiles['user_id'].isnull().sum()

0

In [33]:
import numpy as np

In [36]:
user_profiles.ix[user_profiles.index[(user_profiles.T == np.nan).sum() > 1]]


Empty DataFrame
Columns: [user_id, properties.BG_Schedule, properties.dateOfFirstLaunch, properties.user.diabetes.type, properties.Meal_Reminders_Set, properties.TrackingExerciseMinutes, properties.Total_BG_Reminders, properties.numAppOpenLifeTime, properties.UserTreatmentType, properties.carbBudget, properties.gender, properties.CarbEntryPreference]
Index: []